[package]
name = "bardecoder_ex_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "bardecoder_ex_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
bardecoder = "0.3.0"
image = "0.23"